### ISSUE TITLE
CoinDoubler spawns although there are no coins on a tile

### ISSUE THREAD

**Issue by leonvdhaas** [ATimmeh33/GLAMD-Game-Project#86]
Because coins and CoinDoublers are spawned randomly, sometimes CoinDoublers get spawned without there being any coins on a tile. Please fix this so that CoinDoublers only spawn where there are coins on a tile, and spawn the CoinDoubler on the beginning of the tile. That way the player will profit the most from the bonus. @Legendami

**Comment by Legendami** [comment]
Fixed this. Please check and close ;).
